# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PeaksiOSTesting04' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PeaksiOSTesting04

  target 'PeaksiOSTesting04Tests' do
    inherit! :search_paths
    
    pod 'Quick'
    pod 'Nimble'
  end

  target 'PeaksiOSTesting04UITests' do
    # Pods for testing
  end

end
